apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: eabh1j6qh-java-springboot
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-a2db99c6b2.zvsv.p3.openshiftapps.com/rhtap/rhtap-qe:59653146a070be8c919fe3932784acf4c4c75f91@sha256:c2492b14a528a8a7a66738757571deaa4e5fcc9ad93004c180eecb9222fdf329
          name: container-image
